final List<Map<String, dynamic>> carDetails = [
  {
    "brand": "Jeep",
    "model": "Rubicon",
    "color": "White",
    "type": "Off-road",
    "year": 2024,
    "doors": 4,
    "seatingCapacity": 5,
    "engine": "V6",
    "fuelType": "Petrol",
    "maxSpeed": 180
  },
  {
    "brand": "BMW",
    "model": "M3",
    "color": "White",
    "type": "Coupe",
    "year": 2024,
    "doors": 2,
    "seatingCapacity": 4,
    "engine": "Inline-6",
    "fuelType": "Petrol",
    "maxSpeed": 250
  },
  {
    "brand": "Mercedes-Benz",
    "model": "C-Class AMG",
    "color": "Black",
    "type": "Coupe",
    "year": 2024,
    "doors": 2,
    "seatingCapacity": 4,
    "engine": "V8",
    "fuelType": "Petrol",
    "maxSpeed": 280
  },
  {
    "brand": "Jeep",
    "model": "Rubicon",
    "color": "White",
    "type": "Off-road",
    "year": 2024,
    "doors": 4,
    "seatingCapacity": 5,
    "engine": "V6",
    "fuelType": "Petrol",
    "maxSpeed": 180
  },
  {
    "brand": "BMW",
    "model": "M3",
    "color": "White",
    "type": "Coupe",
    "year": 2024,
    "doors": 2,
    "seatingCapacity": 4,
    "engine": "Inline-6",
    "fuelType": "Petrol",
    "maxSpeed": 250
  },
  {
    "brand": "Mercedes-Benz",
    "model": "C-Class AMG",
    "color": "Black",
    "type": "Coupe",
    "year": 2024,
    "doors": 2,
    "seatingCapacity": 4,
    "engine": "V8",
    "fuelType": "Petrol",
    "maxSpeed": 280
  },
  {
    "brand": "Jeep",
    "model": "Rubicon",
    "color": "White",
    "type": "Off-road",
    "year": 2024,
    "doors": 4,
    "seatingCapacity": 5,
    "engine": "V6",
    "fuelType": "Petrol",
    "maxSpeed": 180
  },
  {
    "brand": "BMW",
    "model": "M3",
    "color": "White",
    "type": "Coupe",
    "year": 2024,
    "doors": 2,
    "seatingCapacity": 4,
    "engine": "Inline-6",
    "fuelType": "Petrol",
    "maxSpeed": 250
  },
  {
    "brand": "Mercedes-Benz",
    "model": "C-Class AMG",
    "color": "Black",
    "type": "Coupe",
    "year": 2024,
    "doors": 2,
    "seatingCapacity": 4,
    "engine": "V8",
    "fuelType": "Petrol",
    "maxSpeed": 280
  },
];
